apiVersion: v1
baseDomain: okd.local
metadata:
  name: lab

compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0

controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 1

networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14 
    hostPrefix: 23 
  networkType: OpenShiftSDN
  serviceNetwork: 
  - 172.30.0.0/16

platform:
  none: {}

fips: false

pullSecret: '{"auths":{"fake":{"auth": "bar"}}}' 
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQD0hNEa6RD1ZC4s871lMEpZ6El0lBYh49usSiyZzszpsghac7sIVuilPXbNG3O+JV7kfevHjZPVpnCGiONEDgVoALqEQGFpGqpiuDWJIevBHDwezEOebgsknwcYHlvbFmvVSlLZYTpp7H9xkIfVP7KpSaJTJpkx6BQ95b03j+7dC5cCsb27s0MJ7Js+mYnTcCXOlHCcpk4srrfYirmorE3ktoTovCQzL8zPzTpAaSrdxTYduoUPMtXmuXImlPPyprY8fpJH1l3J2D2ZGK80b2XT5enK2hKW82YB5evNF7T0em/SgiI4gaAxosaocsuJrDggjsXqyxf/J+Qu8H1tKthUVW15I0N+F0GEJKSUQj6AsspY4pDGfmSlHhN052AGb97LOP8FyRZ9TyFti8rTvwjlcvgWSq/ehXW/NRGXBolPyYpDlzhmahv/b0r7MvE7Zjj/1KsEaZtQVMjRCeE4Pu3Cd5jmXNrsXI+zP8N6ol01L0Cbsxf/bN/OWthsPJuH9TE= root@okd4-services.okd.local'   
